version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    container_name: kafka1

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    container_name: kafka2

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    container_name: kafka3

  booking-service-app:
    image: hotel-reception-booking-service:latest
    environment:
      KAFKA_BROKER_HOST: 'kafka1:9092,kafka2:9093,kafka3:9094'
      JWT_SECRET_KEY: 
      JWT_ISSUER: 

      DB_HOST: 
      DB_PORT: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
    ports:
      - "9000:9000"

    networks:
      - kafka-network
    container_name: booking-service-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

  restaurant-service-app:
    image: hotel-reception-restaurant-service:latest
    environment:
      KAFKA_BROKER_HOST: 'kafka1:9092,kafka2:9093,kafka3:9094'
      SENDER_MAIL: 
      SENDER_MAIL_PASSWORD: 

      JWT_SECRET_KEY: 
      JWT_ISSUER: 

      DB_HOST: 
      DB_PORT: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: 
    ports:
      - "9001:9000"

    networks:
      - kafka-network
    container_name: restaurant-service-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

  room-service-app:
    image: hotel-reception-room-service:latest
    environment:
      KAFKA_BROKER_HOST: 'kafka1:9092,kafka2:9093,kafka3:9094'
      SENDER_MAIL: 
      SENDER_MAIL_PASSWORD: 

    networks:
      - kafka-network
    container_name: room-service-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

  wifi-service-app:
    image: hotel-reception-wifi-service:latest
    environment:
      KAFKA_BROKER_HOST: 'kafka1:9092,kafka2:9093,kafka3:9094'
      SENDER_MAIL: 
      SENDER_MAIL_PASSWORD: 
      
    networks:
      - kafka-network
    container_name: wifi-service-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper

networks:
  kafka-network:
    driver: bridge
